# Generated by Django 4.0.3 on 2024-03-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congressman',
            fields=[
                ('con_id', models.IntegerField(blank=True, null=True)),
                ('dept_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('con_name_kr', models.TextField(blank=True, null=True)),
                ('con_name_en', models.TextField(blank=True, null=True)),
                ('con_name_cn', models.TextField(blank=True, null=True)),
                ('photo_link', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('hp', models.TextField(blank=True, null=True)),
                ('tel_number', models.TextField(blank=True, null=True)),
                ('birth', models.TextField(blank=True, null=True)),
                ('election_record', models.TextField(blank=True, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('party', models.TextField(blank=True, null=True)),
                ('election_detail', models.TextField(blank=True, null=True)),
                ('secretary', models.TextField(blank=True, null=True)),
                ('committee', models.TextField(blank=True, null=True)),
                ('aide', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plenary',
            fields=[
                ('speak_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('confer_num', models.IntegerField(blank=True, null=True)),
                ('confer_name', models.TextField(blank=True, null=True)),
                ('dept_cd', models.IntegerField(blank=True, null=True)),
                ('con_name_kr', models.TextField(blank=True, null=True)),
                ('speaking', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
